tesler-platform/tesler-ui

- src/Provider.tsx
- src/epics/router.ts
**Url example for drilldown with filters:** 
`screen/screenName/view/viewName?filters={"someBcName":"name.contains=11%26status.equalsOneOf=[\\"New\\", \\"Fixed\\"]", "someBcName2": "someField.contains=value"}`
Url parameter "filters" is valid JSON object with bcNames and filters. 
Responsibility for escaping special characters ("%26", "\", etc.) in JSON on whoever writes JSON.
> Support for different types of drilldowns and drilldowns with filters

- src/components/Widget/Widget.tsx
- src/interfaces/widget.ts
> Table widget should support widget-based readOnly flag to avoid unnecessary BC duplication

- src/actions/actions.ts
- src/api/api.ts
- src/components/FullHierarchyTable/FullHierarchyTable.less
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/components/HierarchyTable/HierarchyTable.tsx
- src/components/SameBcHierarchyTable/SameBcHierarchyTable.tsx
- src/components/ui/Popup/Popup.tsx
- src/components/widgets/AssocListPopup/AssocListPopup.tsx
- src/components/widgets/AssocListPopup/AssocTable.tsx
- src/epics/data.ts
- src/hooks/useAssocRecords.ts
- src/interfaces/widget.ts
- src/reducers/view.ts
"Full hierarchy" mode support for associate popup widget. Receives all BC records as plain list and shows it as hierarchy.  
Widget options flags:  
- **hierarchyFull** - Set Full Hierarchy mode for popup widget
- **hierarchyTraverse** - Select/Deselect all ancestors up to root when record is selected/deselected
- **hierarchyGroupSelection** - Select all descendants when record is selected
- **hierarchyGroupDeselection** - Deselect all descendants when record is deselected
- **hierarchyRadio** - Only one root record can be selected at the same time
> Full hierarchy support

- src/Provider.tsx
- src/components/Field/Field.tsx
- src/interfaces/operation.ts
- src/middlewares/autosaveMiddleware.ts
- src/middlewares/requiredFieldsMiddleware.ts
- src/reducers/view.ts
See #1 
* New `requiredFieldsMiddleware` handles `required` fields when widget operation marked with "autoSaveBefore" flag have been requested
* Middlewares now work with correctly typed redux store
* As fields of unknown typed fallback to "input" type, the usual "input" fields and unknown custom fields are handled together. This leads to an error where invalid input fields do not show their validation error hint.
> Required fields validation

- CHANGELOG.md
- package.json
1.1.0 package erroneously included source code instead of js bundle
> Fix broken npm package

- src/assets/i18n/ru.json
- src/middlewares/requiredFieldsMiddleware.ts
- src/reducers/view.ts
* forceActive fields should not drop all existing validation errors.
* requiredFieldsMiddleware incorrectly checked for effective value which could lead to non-empty fields highlighted as empty.
* Russian translation "Required fields are missing" message fix.
> Required fields validation errors

- CHANGELOG.md
- README.md
- package.json
- webpack.config.js
* Webpack config incorrectly referred `LICENSE.MD` instead of `LICENSE`
* Non-working readme links on NPM
> Version update 1.1.2

- src/components/HierarchyTable/HierarchyTable.tsx
- src/epics/data.ts
Multiple BC hierarchy on list type widget loaded only first depth level data.
\+ fix incorrect expand icon position on list type widget
> Fix: List hierarchy loaded only first dept level data.

- CHANGELOG.md
- package.json
* `required` fields validation should be limited to only visible fields, to avoid situations when field is marked as required but user is unable to interact with it (#27).
* `List` widgets erroneously fetched data only for the first level of hierarchy (#25).
* Hierarchy widgets positioned expand icon incorrectly.
> Version update 1.1.3

- src/epics/view.ts
> Fix an infinite loop when a business error is received during a change in a force-active field

- .github/release-drafter.yml
- .github/workflows/build.yml
- .github/workflows/pull-request.yml
- README.md
- webpack.config.js
Push to master branch now initiates publishing of [NPM package](https://www.npmjs.com/package/@tesler-ui/core) and prepares new [GitHub Release draft](https://github.com/tesler-platform/tesler-ui/releases) with list of new commits.
GitHub release is handled via [release-drafter/release-drafter](https://github.com/release-drafter/release-drafter).
`CI` workflow renamed to `Pipeline`.
Add badge in readme file thats shows `Build` workflow status.
`README.md`, `CONTRIBUTING.md` and `CHANGELOG.md` were incorrectly referenced with uppercase extensions and as a result were missing if build was performed from *nix systems.
> Add release workflow

- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/components/HierarchyTable/HierarchyTable.tsx
- src/components/SameBcHierarchyTable/SameBcHierarchyTable.tsx
- src/components/widgets/PickListPopup/PickListPopup.tsx
- src/interfaces/widget.ts
Added hierarchy for PickListPopup
Three types of hierarchy are available: FullHierarchyTable, SameBcHierarchyTable, HierarchyTable
Added new parameter to widget options:
```
hierarchyDisableRoot: boolean
```
This option disables the ability to select a row from the root level.
> Added hierarchy for PickListPopup

- src/components/Field/Field.tsx
- src/components/widgets/TableWidget/TableWidget.tsx
* `PickListField`, `InlinePickList` and `Input` field types now use `InteractiveInput` component to show drilldown button on Table widgets
* `onDrillDown` handler moved to common props due to drilldown flag been equally available for all field types (at least by interfae)
> Table widget should show drilldown button when cell is in edit mode (#64)

- src/actions/actions.ts
- src/epics/data.ts
- src/epics/screen.ts
See #66 
* `postDelete` has been trying to redirect user from record creation for back to the table view by checking and modifying the route, which is not correct if user was not redirected from the table in the first place. 
*  `processPostInvoke` action now accepts `widgetName` as payload and in the future (2.0.0) will require it mandatory.
> New record creation should be cancelable from Table widget (#66)

- src/interfaces/navigation.ts
Broken in #75 due to consumers could already define their own `id` field with different type
> ViewNavigationGroup interface should temporally allow number id until consumers migrate to 2.0.0 (#78)

- src/components/ErrorBoundary/ErrorBoundary.tsx
See [React Error Boundaries](https://reactjs.org/docs/error-boundaries.html)
Usage:
```tsx
import ErrorBoundary from 'components/ErrorBoundary/ErrorBoundary'
const description = `<p><someone@gmail.com></p> `
htmlText = parse(marked(description))
return <ErrorBoundary msg={<p>Невалидный текст</p>}>
<div className={styles.textWidget}>
{htmlText}
</div>
</ErrorBoundary>
```
> Error boundary component to catch render errors

- src/components/ColumnTitle/ColumnTitle.tsx
- src/components/TemplatedTitle/TemplatedTitle.tsx
- src/components/widgets/FormWidget/FormWidget.tsx
- src/utils/strings.ts
See #94 
Tokens are replaced in the template line with the values ​​of the object fields.
If the value is like a date, then convert it to the format 'DD.MM.YYYY' 
Example:
const item = { color1: 'Green', color2: 'Blue' }
const templatedString = 'Color is ${color1} ${color2:Purple} ${color3:Purple}'
format(templateString, item) // => 'Green Blue Purple'
> Support for templates in field names (${name}) for Form and Table widgets

- src/components/HierarchyTable/HierarchyTable.tsx
- src/components/ui/Pagination/Pagination.tsx
See #76 
It is necessary to reset the treeData table cursor when changing the page, because the cursor remains on the last open record of the previous page, and this will break the behavior of the table.
> Reset cursor of treeData table on page change

- src/components/widgets/TableWidget/TableWidget.tsx
see #87 
There were two tricky issues that needed workarounds:
\- Dropdown doesn't call menu visibility change handler when we select menu item.
\- On chrome when we select menu item that is located above some record and menu disappears, onmouseenter event that should change menu button location isn't triggered on that record's row.
Table's onmouseenter event keeps working. I use this event to find record's row under cursor and call handler that process row's mouse enter event.
> Fix table record menu bugs.

- src/interfaces/widget.ts
Added new parameter in WidgetMeta.
```
documentation?: string
```
The parameter is needed to describe the widget in the documentation.
> new WidgetMeta parameter for documentation

- src/actions/actions.ts
- src/assets/i18n/en.json
- src/assets/i18n/ru.json
- src/components/ModalInvoke/ModalInvoke.tsx
- src/components/index.ts
- src/epics/screen.ts
- src/epics/view.ts
- src/interfaces/data.ts
- src/interfaces/operation.ts
- src/interfaces/view.ts
- src/reducers/view.ts
Added the possibility of an additional request to the server after user confirmation.
After customAction is executed, the server response must contain the parameter:
```
preInvoke: {
type: OperationPreInvokeType //must be of type 'confirm' 
message: string  // message for user
}
```
After sending a customAction that will return this parameter, the user will have a modal window. If user confirm this action POST request will be sent to the server with parameter 
```
_confirm = confirmOperation.type
```
The server response may contain new Data parameters and postInvoke actions that will also be executed
> Added PostInvokeConfirm operation

- src/epics/data.ts
- src/reducers/screen.ts
See #113 
Changes:
Instead of loading only widgets BC data, we now search for their ancestors and start loading data from root BCs.
On view change we mark all widgets BC as "loading", because without this mark we can see empty widget without any loading animation until ancestors BC data is loaded.
> Request data for widget BC ancestors (#113)

- webpack.config.js
See #133 
Fix: force tesler-ui to use same moment.js instance as client application, because by default it uses another instance with default locale when there is no any value in datepicker.
> Make datepicker with empty value keep selected locale (#133)

- src/components/ui/MultiField/MultiField.less
- src/components/ui/ReadOnlyField/ReadOnlyField.less
- src/components/ui/ReadOnlyField/ReadOnlyField.tsx
See #140 
Padding styles were moved from multifield to readonly component which is used when field displays simple text.
> Add padding for colored fields (#140)

- src/components/ColumnTitle/ColumnSort.tsx
If path `store.screen.bo.bc[bcName]` is undefined then the page cannot be found.
> fixed an issue with app crash when const page is undefined

- src/components/widgets/TableWidget/TableWidget.tsx
If path `store.screen.bo.bc[bcName]` is undefined then the filterGroups cannot be found.
> Fix an issue with app crash when filterGroups is undefined

- src/middlewares/requiredFieldsMiddleware.ts
See #158 
Returned simplified (because of new typescript capabilities after update) condition to it previous state, because it started to allow undefined values in array that don't expect them.
> Fix app crash on required fields check. (#158)

- src/assets/i18n/en.json
- src/assets/i18n/ru.json
- src/components/ColumnTitle/ColumnTitle.less
- src/components/FileUpload/FileUpload.tsx
- src/components/ui/Pagination/Pagination.tsx
- src/components/ui/PickInput/PickInput.tsx
- src/components/ui/Popup/Popup.tsx
- src/components/widgets/TableWidget/TableWidget.tsx
- src/reducers/view.ts
See #161.
Also addresses the problem with `<TableWidget />` column headers breaking words due to antd default styles.
> Missing i18n tokens (#161), `<TableWidget />` headers should not break words.

- src/components/widgets/AssocListPopup/AssocListPopup.tsx
- src/epics/view.ts
See #171 
Popup pending data changes state was used to save data consistency between multivalue field and popup until user click save button. That's why the cancel button didn't work as expected.
Now we always set initial popup pending changes state from multivalue state on popup opening and clear it on popup save/close.
> Fixed MVG assoc popup wrong cancel button behaviour. (#171)

- src/actions/actions.ts
- src/components/ModalInvoke/ModalInvoke.less
- src/components/ModalInvoke/ModalInvoke.tsx
- src/epics/screen.ts
- src/epics/view.ts
- src/interfaces/data.ts
- src/interfaces/operation.ts
- src/interfaces/view.ts
New implementation of postInvokeConfirm
If the `postInvokeConfirm` parameter is returned in response to the `CustomAction` request, a modal window will appear to confirm the action.
postInvokeConfirm has the following type:
```
{
type: OperationPostInvokeConfirmType, // Type of postInvokeConfirm action
message: string,  // Title for modal
messageContent?: string //Additional text for modal
}
```
there are two types of posInvokeConfirm:
`confirm` - Simple confirmation
`confirmText` - Confirmation with input for user text
> New implementation of postInvokeConfirm

- src/epics/router.ts
When the ChangeLocation action is executed and the ViewName parameter is not specified, then switch to the view from screen.primaryView, instead of screen.views [0]. 
If screen.primaryView is missing too, then use screen.views [0].
> Default screen view as screen.primaryView

- src/components/Field/Field.tsx
See #210 
If our passed property is not defined then it is removed from commonProps and commonInputProps.
> Fix overwriting the default Ant properties of components

- src/assets/i18n/en.json
- src/assets/i18n/ru.json
- src/components/ModalInvoke/ModalInvoke.less
- src/components/ModalInvoke/ModalInvoke.tsx
- src/epics/screen.ts
- src/interfaces/operation.ts
Each custom action may be able to perform an additional Invoke operation before and after its execution. Invoke operation displays a modal window for the user. The action will be executed depending on the contents of the modal window and user actions.
The `ModalInvoke` component can be called by the operations` preInvoke` and `postInvoke`. In general, `preInvoke` is an indicator that the next `postAction `implements a condition for further behavior. However, `ModalInvoke` can be used as a reaction to `preInvoke` in simple behavior.
In this case, it is necessary for `ModalInvoke `to be able to process all types of Invoke.
`ModalInvoke` component have been changed, allowing to display modal windows for `info` and `error` invoke types.
* type `info` displays a warning. Сlick on the button is …
> Add Modal Invoke window for info and error invoke types (#216)

- src/index.ts
- src/interfaces/widget.ts
- src/middlewares/requiredFieldsMiddleware.ts
* Fix the problem of #257
* Export `TableLikeWidgetTypes` array for some shared features between table like widgets; intention is that it's available for customization by client app, although we might move to a getter instead
> Autosave middleware reserved for tables erroneously applied to other widgets by `requiredFieldsMiddleware` (#257)

- src/epics/data.ts
- src/interfaces/widget.ts
Epics `bcFetchDataEpic` and `bcLoadMore` takes into consideration `limit` value from widget metadata, at first. If it is zero then `limit` value from BC metadata will be taken. (#261)
> Consideration of `limit` from widget metadata 

- src/components/widgets/TableWidget/TableWidget.test.tsx
- src/components/widgets/TableWidget/TableWidget.tsx
This prop allows to pass custom component to column title (#218)
For example:
```columnTitleComponent={() => <div>Some title</div>}```
or
```
import {TableWidget as CoreTableWidget} from '@tesler-ui/core'
...
function TableWidget(props: TableWidgetProps) {
const renderColumnTitle = React.useCallback(
(pr: {widgetName: string, widgetMeta: WidgetListField, rowMeta: RowMetaField}) =>
<CustomColumnTitle
widgetName={pr.widgetName}
widgetMeta={pr.widgetMeta}
rowMeta={pr.rowMeta}
/>,
[]
)
return <CoreTableWidget
{...props}
columnTitleComponent={renderSmColumnTitle}
/>
}
```
> TableWidget: Added `columnTitleComponent` prop

- package.json
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
alpha version ^1.15.8-alpha.0
Fixes:
- PreInvokeMiddleware
- Select all checkbox in FullHierarchyTable
- Basis for the save number of Tablewidget records
- FullHierarcy search support
- PickListPopup remove footer buttons and fix title
- MVG field open icon inactive without popup widget rowMeta
- confirm popup BC
- wait data and rowMeta in HierarcyTable on ListWidget
- default expand level up
> Alpha version ^1.15.8-alpha.0

- .github/workflows/build-alpha-from-pr.yml
If you have PR and would like to check your feature before merge, then just leave the comment `/alpha` under your PR.
Let  current version of package be `1.15.0`. 
Workflow checks if NPM registry contains alpha versions of that package. 
If doesn't contains, then version `1.15.0-alpha0` will be published. 
If contains, then workflow will increase present version. For example: `1.15.0-alpha1` -> `1.15.0-alpha2`
With this workflow  there is no need in `alpha` branch.
> Added workflow which allows to build `alpha` package

- package.json
- tsconfig.json
- webpack.config.js
- yarn.lock
There was the mistake in PR #281 
Let's consider reasons as chain of facts:
1. Old version of `tsconfig.json` contained option `"outDir": ""`
2. In PR #281 `ts-loader` has been upgraded to `6.2.2`
3. New version of `ts-loader` according to option `"outDir": ""` generates declaretion files in current directory.
Thats why option `"outDir": "dist"` has been added.
That was the reason of next error:
While compiling `ts-loader` concatinates pathes from option `"outDir": "dist"` of `tsconfig.json` and `output.path` of `webpack.config.js`. Thats why there was another `dist` folder in `dist` folder.
In this PR `tsconfig.json` was fixed by option `"outDir": "./dist"`. It leads to correct structure in `dist` folder.
> Fixed configuration

- .github/workflows/build-alpha-from-pr.yml
This PR is update for #308
This PR adds next check:
Is whether user who add comment to PR  is member of team `tesler-team`.
> Fix: only `tesler-team` members can build alpha package

- src/components/FullHierarchyTable/FullHierarchyTable.less
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
Now you can set the column width in FullHierarchyTable
To do this, in the widget meta in the field description, you need to add key `width: string | number`
```
{ key: "fieldKey", title: "fieldTitle", type: "input", width: "100px" }
```
or
```
{ key: "fieldKey", title: "fieldTitle", type: "input", width: 100 }
```
> Alignment of columns in the FullHierarchyTable, due to setting the width

- .github/workflows/build-alpha-from-pr.yml
As there is no availability to use GITHUB_TOKEN to acсess team members, now set my personal token
> Changed login to personal

- .github/workflows/build-alpha-from-pr.yml
There was the bug with pipeline `build-alpha-from-pr.yml`:
The action `actions/checkout@v2` checks out `master` branch instead head branch of a pull request.
This PR provides next improvements:
- Step: get PR from commentation event
- Step: get branch name from PR
- Set `ref` to action `actions/checkout@v2`
> Fixed checkout to branch from PR

- src/epics/router.ts
- src/reducers/screen.ts
Drildown with filters can remove all filters on current BC (#360). 
Filter url must contain JSON in which the `filters` parameter is specified, containing name of the BC. The filter string must be empty.
Example drilldown url: 
`"/screen/view?filters={"bcName":""}"`
------------------------
Bugfix:
When filter with an empty value is added to a table column, the bcRemoveFilter filter cleanup action will be executed (ColumnFilter.tsx 104). bcRemoveFilter action was crash if bc have current filters in this case.
> Drildown with filters ability remove filter

- CHANGELOG.md
- src/middlewares/requiredFieldsMiddleware.ts
> Incorrect check for `autoSaveBefore` in 1.18.0 causes required fields validation when it shouldn't (e.g. cancel operations) (#368)

- src/epics/view.ts
- src/interfaces/operation.ts
- src/interfaces/widget.ts
- src/middlewares/autosaveMiddleware.ts
Custom action autosave (#387)
**Feature:** Autosave pending data by custon widget save action.
New ability to autosave by custom action on form widgets when have only custom actions. Required when user has input form and initiated drilldown.
New widget meta param `defaultSave` is name default no crud save action
_**Example:**_
``` ts
"name": "Widget Name",
"title": "Widget Title",
"type": "Form",
"bc": "bcName",
...
"options": {
"actionGroups": {
"include": [
"custom-save",
"custom-cancel"
],
"exclude": [
"custom-edit",
],
"defaultSave": "custom-save"
},
...
},
}
```
When user input part or full Form and initial any `drillDown`, action `"defaultSave": "custom-save"` will be executed. But if custom save action `"defaultSave": "custom-save"` have `postAction` `drillDown`, then `postAction` …
> Custom action autosave

- src/components/ColumnTitle/ColumnFilter.tsx
- src/components/widgets/AssocListPopup/AssocListPopup.tsx
MVG filter, dataItem keys (#371).
This filter of values ​​is not needed, because if `dataItems` ​​are present in `selectedRecords`, then they are selected for the filter values.
> MVG filter, dataItem keys.

- .github/workflows/build-alpha-from-pr.yml
There was a bug in alpha build workflow while version comparison.
If list of versions is:
```
1.18.2-alpha0
1.18.2-alpha1
1.18.2-alpha10
1.18.2-alpha2
1.18.2-alpha3
1.18.2-alpha4
1.18.2-alpha5
1.18.2-alpha6
1.18.2-alpha7
1.18.2-alpha8
1.18.2-alpha9
1.18.2
```
Then result of command `sort -r` is:
```
1.18.2-alpha9
1.18.2-alpha8
1.18.2-alpha7
1.18.2-alpha6
1.18.2-alpha5
1.18.2-alpha4
1.18.2-alpha3
1.18.2-alpha2
1.18.2-alpha10
1.18.2-alpha1
1.18.2-alpha0
1.18.2
```
So this PR fix command to `sort -Vr`, which result is:
```
1.18.2-alpha10
1.18.2-alpha9
1.18.2-alpha8
1.18.2-alpha7
1.18.2-alpha6
1.18.2-alpha5
1.18.2-alpha4
1.18.2-alpha3
1.18.2-alpha2
1.18.2-alpha1
1.18.2-alpha0
1.18.2
```
> Alpha build version comparison was fixed

- src/interfaces/bc.ts
- src/reducers/screen.ts
Added new string param in BcMeta: `defaultFilter`.
Example of `defaultFilter` value: 
'someField1.contains=someValue
&someField2.equalsOneOf=%5B%22someValue1%22%2C%22someValue2%22%5D'
See #399
> Support for default filters

- src/components/widgets/AssocListPopup/AssocListPopup.tsx
AssocListPopup Tag broken (#393)
If `AssocListPopup` have many records and page pagination active, when showed `Tag` items only from current page. And cannot show `Tag` hidden counter because limit dataitems = tag limit as default. `Tag` dataitems match from current page data filtered by `pendingDataChanges` by function `useAssocRecords` and used only dataitems of current page.  
Change match `Tag` items from `pendingDataChanges` with `_associate` flag.
> AssocListPopup Tag

- src/components/FilterPopup/FilterPopup.tsx
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/components/FullHierarchyTable/utils/useExpandedKeys.ts
- src/components/FullHierarchyTable/utils/useHierarchyCache.ts
- src/epics/data.ts
- src/interfaces/widget.ts
FullHierarchy search enhancement (#403).
**_Feature_**
New `FullHierarchy` widget meta option:
``` ts
hierarchyDisableDescendants?: boolean
```
Means that `FullHierarchy` search result should not include descendants of found elements.
**_Bug fix_**
`<FilterPopup>` component should not do `bcForceUpdate` when a filter is _applied_ or _cleared_ on a `FullHierarchy`.
**_Bug fix_**
Data epic did not transfer `filters` param for `FullHierarchy` backend query. `sorters` parameters unchanged.
> FullHierarchy search enhancement

- src/epics/data.ts
See #406
Action `saveAssociations` can perform `postInvoke` actions. PostInvoke implement for `caleeBC`, whitch initiate `AssocListPopup`.
> saveAssociations action postInvoke support

- src/components/widgets/AssocListPopup/AssocListPopup.test.tsx
- src/components/widgets/AssocListPopup/AssocListPopup.tsx
- src/epics/view.ts
See  (#418).
Add processing empty filter values MVG fields. Empty MVG field filter value should not be stored. Empty value means that the filter for this field should be cleared if exist current filter values for this field.
Removed pending data view update in favor of the `useAssocRecords` utility. (Bug when open popup after delete filter - show previos data assoc. Reopen popup without assoc.)
> MVG field empty filter

- src/utils/__tests__/filters.test.ts
- src/utils/filters.ts
Broken by [#430](https://github.com/tesler-platform/tesler-ui/pull/430/files#diff-b43c7ecdde65a63b9d877c9da877c710R84)
> parseFilters should return null instead of empty array

- src/epics/router.ts
- src/reducers/screen.ts
Rewrite for handling inner drilldowns with filters:
1) Existing filters are cleared only when drilldown specifies its own filters or explicitly says that filters should be cleared via empty string filter expression. Otherwise filters are preserved, the same way as they are preserved when navigating between views via menu.
2) Drilldown to the same view with explicit clearing of filters now should correctly fire `bcForceUpdate` (adressess #374)
3) Empty filters now completely removed from the store instead of hanging with empty objects leading to various checks throughout the code thinking that filters are set for the BC
> More clear epic for handling drilldown filters, do not put empty filters in the store (#374)

- src/components/ui/Multivalue/MultivalueTag.less
- src/components/ui/Multivalue/MultivalueTag.tsx
See #453 
Added an event to an empty area of ​​the `multivalue` field between `Tag`. The event repeats the event of clicking on the folder icon and is available after loading the popup metadata. Available only when the field is active. Child elements as `Tag` do not inherit behavior.
> MVG field. Clickable empty area.

- src/components/Field/Field.tsx
- src/components/widgets/FormWidget/FormWidget.tsx
- src/epics/data.ts
- src/interfaces/view.ts
- src/middlewares/__tests__/requireFieldsMiddleware.ts
- src/middlewares/requiredFieldsMiddleware.ts
- src/reducers/view.ts
See #441 
A target form of the interface of `pendingValidationFails` is looks like:
```
pendingValidationFails?: PendingValidationFails
```
where `PendingValidationFails` is:
```
interface PendingValidationFails {
[bcName: string]: {
[cursor: string]: Record<string, string>
}
}
```
I provide temporary solution for backward compatibility until `2.0.0` release will be released.
Temporary interface for `pendingValidationFails` looks like this:
```
pendingValidationFails?: Record<string, string> | PendingValidationFails,
```  
I've added `pendingValidationFailsFormat` as flag of `target` or `old` formats of `pendingValidationFails`.
Currently, if you'd like to use target version of `pendingValidationFails`, you can simply set
```pendingValidationFailsFormat: …
```
> `pendingValidationFails` are divided by BC names and cursors (#441)

- src/epics/__tests__/data/removeMultivalueTag.test.ts
- src/epics/data.ts
- src/tests/testEpic.ts
`testEpic` utility.
Usage:
1) mock `store`
2) create `action`
3) apply `action` and `store` to imported `epic`
4) pass `epic` to `testEpic` and check epic result actions in callback
> `testEpic` utility for unit testing epics and example for `removeMultivalueTag` test

- src/components/ui/Multivalue/MultivalueTag.tsx
- src/components/widgets/AssocListPopup/AssocListPopup.tsx
- src/epics/__tests__/data/removeMultivalueTag.test.ts
- src/epics/data.ts
- src/epics/data/removeMultivalueTag.ts
- src/epics/view.ts
- src/index.ts
- src/tests/testEpic.ts
- src/utils/tree.ts
See #443 
`hierarchyTraverse` diselect bugfix. 
Additional filter for `wasLastInData` has been added to `currentLevelData` check, which excludes from `currentLevelData` array those that have been diselected.
MVG field tags will inherit behavior delete items from the hierarchy widget with which it is associated. Unavailable close option before AssocPopup is ready.
**_bugfix:_**
- Application crach when `AssocPopup` widget is not Hierarchy without `meta.options`
- Fix match popup pendingChanges for not Hierarchy `AssocPopup`
> hierarchyTraverse diselect bugfix. MVG field hierarchy behavior.

- src/epics/router.ts
See #484 
Fix console warning. Showed only if filter or sorter JSON of `drillDown.inner` have parsing error and dont show if `drillDown.inner` without this params.
> drillDown.inner fake console warning

- src/epics/__tests__/data/removeMultivalueTag.test.ts
- src/epics/data/removeMultivalueTag.ts
- src/middlewares/requiredFieldsMiddleware.ts
- src/reducers/view.ts
See #478
Process of checking hierarchy options and actions on them has been changed.
Hierarchy options have different logic for changing elements in callee BC and popup BC, depending of type hierarchy. These options have their own branches.
There was no branch for changing dataItem if popup widget is not hierarchy. In this case, you need to change dataItem for callee BC and popup BC. This is the default branch of `removeMultivalueTag` Epic.
Validation errors reset pending data to `null`. This values ​​are not involved in the math popup tags.
Now validation error used `[]` for array like empty objects. With empty pendingData as `[]` action `showViewPopup` works correctly.
> Remove Multivalue tag bugs

- src/api/api.ts
- src/epics/data.ts
- src/utils/__tests__/cancelRequestEpic.test.ts
- src/utils/api.ts
- src/utils/cancelRequestEpic.ts
See #486 
There is added `createCanceler` utility. It returns new `axios.CancelToken` and callback function which performs request cancelation.
Also `cancelRequestEpic` is added. It's a utility epic.
It gets:
- an observable input
- list of action types which triggers cancel
- a callback of request cancelation
- an action creator which called by request cancelation
- Optional callback function which filters come actions
Returns an epic which cancels request and dispatches cancel action
> Cancelation of `data` and `row-meta` requests is added (#486)

- src/epics/data.ts
- src/epics/data/__tests__/bcFetchDataEpic.test.ts
See #495 
Fix bug of `bcForceUpdate` when using `LoadMore` pagination. Requesting data from first page to current when update widget with pagination `LoadMore`.
> Pagination `LoadMore` update BC request fix

- src/components/FullHierarchyTable/FullHierarchyTable.less
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/interfaces/widget.ts
- src/utils/hierarchy.ts
Changes have been made to the calculation of column widths and paddings in the hierarchy. New function `getColumnWidth` calculates column width based on the table data.
`WidgetFieldBase` interface has been expanded. Added the `hierarchyShift?: boolean` parameter, which indicates that this column should be shifted in accordance with the hierarchy level at which it is located.
Field option `hierarchyShift` allow set a custom view of the hierarchy. 
Column width is not available for the last column. The remaining width of the last column is calculated by the Ant lib when rendering table.
> Hierarchy values shift

- src/components/ui/TreeVirtualized/TreeVirtualized.tsx
- src/components/ui/TreeVirtualized/__tests__/TreeVirtualized.test.tsx
- src/utils/tree.ts
If `<TreeVirtualized />` has more items than fit into display window, it can be difficult to find required item with automation tests drivers such as Selenium.
This PR adds `scrollToItem` function to DOM element of `<TreeVirtualized />` component which can be called by JS executor from Selenium tests.
> console helper `scrollToItem` for automation testing of `<TreeVirtualized />` components

- src/components/ColumnTitle/ColumnFilter.tsx
- src/components/Field/Field.test.tsx
- src/components/Field/Field.tsx
- src/components/FileUpload/FileUpload.tsx
- src/components/FilterPopup/FilterPopup.tsx
- src/components/InlinePickList/InlinePickList.tsx
- src/components/Multivalue/MultivalueField.tsx
- src/components/PickListField/PickListField.tsx
- src/components/ui/DatePickerField/DatePickerField.tsx
- src/components/ui/Dictionary/Dictionary.test.tsx
- src/components/ui/Dictionary/Dictionary.tsx
- src/components/ui/Multivalue/MultivalueHover.tsx
- src/components/ui/NumberInput/NumberInput.tsx
- src/components/ui/RadioButton/RadioButton.test.tsx
- src/components/ui/RadioButton/RadioButton.tsx
- src/components/ui/ReadOnlyField/ReadOnlyField.tsx
- src/components/ui/TextArea/TextArea.test.tsx
- src/components/ui/TextArea/TextArea.tsx
- src/components/widgets/AssocListPopup/AssocListPopup.test.tsx
- src/components/widgets/AssocListPopup/AssocListPopup.tsx
- src/components/widgets/TableWidget/TableWidget.test.tsx
- src/components/widgets/TableWidget/TableWidget.tsx
- src/epics/router/drilldown.ts
- src/hooks/useWidgetFilter.ts
- src/interfaces/filters.ts
See #482
**SearchHighlight enhancement**
Expanded filter object interface `bcFilter`. This allows identify widget by which filter is applied. With this change, it became possible to exclude incorrect highlighting of filtered text in widgets without filters on same BC.
``` ts
export interface BcFilter {
type: FilterType,
fieldName: string,
value: DataValue | DataValue[],
viewName?: string,     // new field
widgetName?: string    // new field
}
```
Added search highlighting in the following field types (only with `readOnly: true` flag):
- Dictionary
- Date like
- Multivalue
- Text
_NOTE1:_ `Multivalue` highlighting based on presence `displayedValue` key. If key is present dataItem has displayed string, then current field record is highlighted.
_NOTE1:_ If backend use `drillDown` with …
> Extension filter object interface `bcFilter`. SearchHighlight enhancement.

- src/components/Field/Field.test.tsx
- src/components/Field/Field.tsx
- src/components/ui/ReadOnlyField/ReadOnlyField.tsx
- src/epics/router.ts
- src/hooks/useDrillDownUrl.ts
- src/interfaces/rowMeta.ts
- src/interfaces/widget.ts
Url can be taken from field data by given drillDownKey, otherwise stays default drilldown behaviour
> Ability to override drilldown link by adding drillDownKey in row meta

- src/epics/view.ts
Same as #536 without refactoring
> `showAssocPopup` epic will crash when Tesler API returns null instead of empty array, which it will for SQL BC

- src/components/Field/Field.tsx
- src/components/ui/ReadOnlyField/ReadOnlyField.tsx
- src/hooks/useDrillDownUrl.ts
Removed useDrillDownUrl from ReadOnlyField, widgetName replaced by bcName for widgets with different bc
> FIX: useDrillDownUrl replace widgetName by bcName

- src/epics/data.ts
- src/utils/__tests__/bc.test.ts
- src/utils/bc.ts
* `requestBcChildren` utility moved to `utils/bc.ts` and renamed to `getBcChildren`
* test coverage for this utility
* contract changed to accept widgets and BC dictionary instead of accessing global store instance
* implementation refactored: hierarchy logic split into separate function, simplified code, optional chaining removed when it was not working (never hit due to outer condition check or neighboring code accessing the same properties without chaining)
> `requestBcChildren` utility moved to `utils/bc.ts`, test coverage

- src/components/FullHierarchyTable/FullHierarchyTable.less
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
In full hierarchy tables **table-layout: fixed** style was applied to table **\<div/>** container instead of **\<table/>** itself, that caused inconsistency in separate inner table sizes.
> Full hierarchy column sizes fix

- src/actions/actions.ts
- src/api/api.ts
- src/epics/router.ts
- src/epics/router/__tests__/handleRouter.test.ts
- src/epics/router/handleRouter.ts
- src/epics/view/fileUploadConfirm.ts
- src/index.ts
- yarn.lock
dAlso:
- strict typedoc version
- `fileUploadConfirmImpl` description referencing itself instead of `fileUploadConfirm`
- replace deprecated `ObjectMap` with `Record` for `GetParamsMap` type
> `handleRouter` epic tests

- src/epics/data.ts
- src/reducers/screen.ts
See #566 
View selection shouldn't mark all its BCs as loading (see #530)
Otherwise we can reach next situation:
Let it be a view includes widget with BC `exampleBc` and type which is  included into `skipWidgetTypes`. If there is no one else widget with BC `exampleBc` then there is no data loading for `exampleBc` in fact. But action of view selecting has marked `exampleBc` as loading already. So if an application has only one such widget  then `exampleBc` become marked as loading permanently.
> If record is present, cursor shouldn't be reset (#566)

- src/components/HierarchyTable/HierarchyTable.tsx
indent column optional behaviour as in full hierarchy table, ability to set column width manually
> HierarchyTable layout fix

- src/components/ui/MultiField/MultiField.less
- src/components/ui/MultiField/MultiField.tsx
Old styles caused error with colored fields, because text go beyond colored area.
Also it caused problems with long noncolored fields, because text didn't wrap.
Now colored fields don't have width restriction, and long text also wrap.
> fix MultiField styles

- src/components/FullHierarchyTable/utils/useExpandedKeys.ts
Full hierarchy is reopened after any record select
> fix full hierarchy reopen after record select

- package.json
- src/interfaces/data.ts
- src/interfaces/navigation.ts
- src/interfaces/operation.ts
- src/interfaces/router.ts
- src/interfaces/view.ts
- src/interfaces/widget.ts
- yarn.lock
There are a lot of types that declared in Tesler UI while in fact those types describe both frontend entities and parts of screen/view/widget/sqlbc JSON descriptions which are stored in backend side of the application, which leads us to:
1) To generate JSON schemas we'll have to keep a separate instance of all the types in [@tesler-ui/schema](https://github.com/tesler-platform/tesler-schema), which is a double work and will definetly end up out of sync with each outher
2) This types being declared in Tesler UI are encouraging developers to modify the public contract which is in fact also affects how [Tesler API](https://github.com/tesler-platform/tesler) processes JSON descriptors for application entities.
Extracting them into separate repository will allow us to have a single source of …
> Remove backend-affecting types and reexport them from "@tesler-ui/schema"

- src/components/FilterPopup/FilterPopup.tsx
- src/components/ui/FilterField/FilterField.test.tsx
- src/components/ui/FilterField/FilterField.tsx
See issue #593
Changes have been made to the filter processing for checkbox column type.
Checkbox filter control incorrectly uses the event field that changes the indicator checkbox.
`e.target.value` instead `e.target.checked` (FilterField.tsx)
Need change the filter handler behavior. Filter value `false` for it should be subject-specific, not just empty, which means clear filter.
Please check correctness of my solution, and let me know if the fix is accepted so that I can update `tesler-ui` version in my app.
> TableWidget filter for Checkbox field types

- src/Provider.tsx
- src/epics/router/__tests__/changeLocation.test.ts
- src/interfaces/store.ts
- src/reducers/router.ts
- src/utils/__tests__/configureStore.test.ts
- src/utils/configureStore.ts
At the moment there is no obvious way to override Tesler reducer reacting to built-in action:
https://github.com/tesler-platform/tesler-ui/blob/668d0d2d69f15e256649aabbecd80c4563b0a29b/src/interfaces/store.ts#L24-L26
ClientReducer type provides `override` flag and it is in fact respected, but it is conceptionally flawed in a way that most projects treat slice reducer as a single function with a giant `switch` inside, so this flag will replace reducers for the entire store slice.
This has absolutely no usage in real life and will be removed 2.0.0
Two other currently available options:
1) Use custom action type - not always convinient as Tesler action might be dispatched deeply from Tesler epic or component so overriding reducer for one action will require a large chunk of code from client …
> provide original store slice state before in went through Tesler reducer as a reducer argument to allow overriding built-in behavior

- src/actions/actions.ts
- src/epics/data/bcFetchData.ts
- src/epics/data/bcSelectDepthRecord.ts
- src/reducers/__tests__/data.test.ts
- src/reducers/data.ts
- src/reducers/screen.ts
1) Lazy widgets should not skip their fetch when they are shown
2) `parentOfNotLazyWidget` condition does not actually checked if widget is lazy or not, so any child widget matched
3) `anyHierarchyWidget` and `fullHierarchyWidget` condition checked bcName from action payload instead of widget, meaning requested from business components on ensted hierarchy levels were not detected as coming from hierarchy widget.
All this contributed to hierarchies not showing expanded nodes content after https://github.com/tesler-platform/tesler-ui/pull/596 
Additionally there is a clean up for reducers from `<SameBcHierarchyTable />` stuff and additional deprecation tags.
> lazy load erroneously applied to nested BC in hierarchies

- CHANGELOG.md
- package.json
- src/actions/actions.ts
- src/components/Widget/Widget.test.tsx
- src/components/widgets/FlatTree/FlatTreePopup.tsx
- src/components/widgets/FlatTree/__tests__/FlatTreePopup.test.tsx
- src/components/widgets/FlatTree/useSingleSelect.ts
- src/components/widgets/PickListPopup/PickListPopup.tsx
- src/epics/data/__tests__/bcFetchData.test.ts
- src/epics/data/bcFetchData.ts
- src/epics/view/__tests__/fileUploadConfirm.test.ts
- src/epics/view/fileUploadConfirm.ts
When processing `bcFetchData` epic after navigating to a different view where the requesting widget is not present, epic will crash.
Additionally deprecate `bcName` payload for `closeViewPopup` action as it is not used and can't be realistically used as:
1) only one popup can be active on a view
2) not all popups on a view have business component
> stale data fetch epic can crash the application

- src/components/ui/Multivalue/MultivalueHover.tsx
It's hard to tell if such thing as "arrow icon" is needed here at all, as originally it came with matching icon in true branch; possibly some garbage code.
While investigating though what we can definetly do is to disable this thing when no drilldown callback provided in props, meaning this icon is completely useless.
> `<MultivalueHover />` should not show arrow icon when no drilldown handler available

- .github/workflows/build-alpha-from-pr.yml
- .github/workflows/documentation-tests.yml
Now **you should be member of Tesler Team** to use `Run doc tests` workflow
Now `check-commentator` job uses secret
> check-commentator job is added to `Run doc tests` workflow

- src/middlewares/__tests__/requiredFieldsMiddleware.test.ts
- src/middlewares/requiredFieldsMiddleware.ts
- src/reducers/__tests__/view.test.ts
- src/reducers/view.ts
- src/utils/__tests__/operations.test.tsx
- src/utils/operations.ts
According the description #612 the reason of circular calling actions `sendOperation` with type `save` and `selectTableCellInit` is stale data in `selectedCell`. 
`selectedCell` isn't reseted after successful creating new table and it cheat on `autosaveMiddleware` [here](https://github.com/tesler-platform/tesler-ui/blob/master/src/middlewares/autosaveMiddleware.ts#L42) while processing of action `selectTableCellInit`.
Also `requiredFieldsMiddleware` reacts on `sendOperation` action with type `OperationTypeCrud.save`. This operation has `autoSaveBefore` flag. Since this operation is called on table widget `requiredFieldsMiddleware` calls `selectTableCellInit` action.
Hence we go to close loop.
To brake the loop we need to clear `selectedCell` by `bcNewDataSuccess` action . 
Also …
> `bcNewDataSuccess` resets selectedCell;  `operationRequiresAutosave` of `requiredFields` middleware ignores save operation (#612)

- .github/workflows/coverage.yml
Unit tests and coverage workflow fires twice for each commit: once when pull request is opened and results are shown in PR, and once again when PR is merged and workflow results are not used anywhere.
> coverage pipeline run twice on opened pull request

- src/middlewares/__tests__/requiredFieldsMiddleware.test.ts
- src/middlewares/requiredFieldsMiddleware.ts
- src/utils/__tests__/operations.test.tsx
- src/utils/operations.ts
See #654 
Actually, it's reverting part of #637 which ignoring `autoSaveBefore` flag on save operation in `requiredFieldsMiddleware`.
> The record is saved with empty required fields

- src/utils/history.ts
> malformed url parameters were treated as part of `bcPath` which lead to failing requests to Tesler API (#663)

- src/components/ColumnTitle/ColumnFilter.tsx
Apparently was broken [here](https://github.com/tesler-platform/tesler-ui/pull/621/files#diff-010281f09484714335e1982d158d2eb1424c3f4bffdbe45c051e3b7415f8162dR76) by passing `widgetName` in `showViewPopup` reducer but assigning it with widget's own name for multivalue fields, filters for which reuse same logic as picklists.
Also `multivalueHover` should be considered the same as `multivalue` for the purposes of column filtration
> `<ColumnFilter />` fails to open filtration popup for multivalue fields

- src/epics/data/__tests__/bcFetchData.test.ts
- src/epics/data/bcFetchData.ts
see #698
Consider the following example:
An action `bcFetchDataRequest` with payload `{widgetName: 'exampleWidgetName', bcName: 'grandParentBcName'}` is dispatched.
Let bcName of 'exampleWidgetName' has name 'exampleWidgetBcName'. Also 'exampleWidgetName' includes `showCondition` with `bcName: 'parentBcName'`. And hierarchy of BC names is: 'grandParentBcName' is parent of 'parentBcName', 'parentBcName' is parent of 'exampleWidgetName'. Also current `view` doesn't include other widgets with BC name 'parentBcName' or 'grandParentBcName'.
In this case `bcFetchData` epic should load data of whole hierarchy of BCs from 'grandParentBcName' to 'exampleWidgetBcName'.
> `bcFetchData` should load data of hierarchy of BCs

- package.json
- src/assets/styles/theme.less
- src/components/index.ts
- src/components/ui/NavigationTabs/NavigationTabs.less
- src/components/ui/NavigationTabs/NavigationTabs.test.tsx
- src/components/ui/NavigationTabs/NavigationTabs.tsx
- src/components/widgets/NavigationTabsWidget/NavigationTabsWidget.test.tsx
- src/components/widgets/NavigationTabsWidget/NavigationTabsWidget.tsx
- src/components/widgets/ViewNavigationWidget/ViewNavigationWidget.test.tsx
- src/components/widgets/ViewNavigationWidget/ViewNavigationWidget.tsx
- src/hooks/useViewTabs.ts
- src/interfaces/widget.ts
- src/utils/viewTabs.ts
- yarn.lock
See #702
The purpose of the widget is to display navigation tabs depends on position in view's metadata. In other words this widget should be included in widgets stream.
The widget displays the same component as `NavigationTabsWidget`.
But this widget should be used in case need to exclude navigation  from widgets stream.For instance, client could decide to fix it on top of the screen.
> `ViewNavigationWidget` and `NavigationTabsWidget` are added

- src/reducers/router.ts
See #749
The reason of the problem is in search params of `location` object. See the picture below:
The `params` which comes from `historyObj.location` has URLSearchParams type. Whereas the `params` from redux store is a plain object.
They wouldn't never be equal. So decided to ignore them as it already was done [here](https://github.com/tesler-platform/tesler-ui/blob/master/src/epics/router/drilldown.ts#L103).
> URLSearchParams are ignored when comparing locations (#749)

- CHANGELOG.md
- package.json
- src/reducers/router.ts
* URLSearchParams are ignored when comparing locations [#749](https://github.com/tesler-platform/tesler-ui/issues/749)
> Release 1.34.2
