- src/components/Widget/Widget.tsx
- src/epics/data.ts
> Restore missing commits from internal 0.1.58 build

- src/components/Field/Field.test.tsx
- src/components/Multivalue/MultivalueField.test.tsx
- src/interfaces/bc.ts
- src/reducers/screen.ts
- src/utils/__tests__/filters.test.ts
- src/utils/filters.ts
> Support BC property "defaultSort"

- CHANGELOG.md
- CONTRIBUTING.md
- package.json
- webpack.config.js
See [CHANGELOG.MD](https://github.com/tesler-platform/tesler-ui/pull/13/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)
> Version update 1.1.0

- CHANGELOG.md
- CONTRIBUTING.md
- package.json
- src/Provider.tsx
- src/actions/actions.ts
- src/api/api.ts
- src/components/Field/Field.test.tsx
- src/components/Field/Field.tsx
- src/components/FullHierarchyTable/FullHierarchyTable.less
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/components/HierarchyTable/HierarchyTable.tsx
- src/components/Multivalue/MultivalueField.test.tsx
- src/components/SameBcHierarchyTable/SameBcHierarchyTable.tsx
- src/components/Widget/Widget.tsx
- src/components/ui/Popup/Popup.tsx
- src/components/widgets/AssocListPopup/AssocListPopup.tsx
- src/components/widgets/AssocListPopup/AssocTable.tsx
- src/epics/data.ts
- src/epics/router.ts
- src/hooks/useAssocRecords.ts
- src/interfaces/bc.ts
- src/interfaces/operation.ts
- src/interfaces/widget.ts
- src/middlewares/autosaveMiddleware.ts
- src/middlewares/requiredFieldsMiddleware.ts
- src/reducers/screen.ts
- src/reducers/view.ts
- src/utils/__tests__/filters.test.ts
- src/utils/filters.ts
- webpack.config.js
See [CHANGELOG.MD](https://github.com/tesler-platform/tesler-ui/pull/14/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)
> Release 1.1.0

- src/middlewares/requiredFieldsMiddleware.ts
> `required` fields validation should be limited to only visible fields

- CHANGELOG.md
- package.json
- src/components/HierarchyTable/HierarchyTable.tsx
- src/epics/data.ts
- src/middlewares/requiredFieldsMiddleware.ts
See [CHANGELOG.MD](https://github.com/tesler-platform/tesler-ui/blob/9a7a0457aa997fa06d96103dbdbbd12cc933e905/CHANGELOG.md#version-113)
> Release 1.1.3

- src/epics/data.ts
> Remove _limit and _page params from full hierarchy data request.

- CHANGELOG.md
- package.json
* Remove `limit` and `page` params from full hierarchy data request (#34).
* Fix an infinite loop when a business error is received during a change in a force-active field (#35).
* Add pull request pipeline
> Version update 1.1.4

- src/components/Multivalue/MultiValueListRecord.less
- src/components/Multivalue/MultiValueListRecord.tsx
> Increase indent between multi-value list records

- src/components/Field/Field.tsx
- src/components/ui/Dictionary/Dictionary.tsx
- src/epics/view.ts
- src/reducers/view.ts
See #46 
Also fix console error, that appears when trying to check force active fields change on full hierarchy BC without data.
> Bug: Fields ignores empty delta value.

- src/epics/router.ts
Fixed bug with the lack of data after drilldown on the same view
> Update Data after drildown on same View

- CHANGELOG.md
- package.json
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/components/HierarchyTable/HierarchyTable.tsx
- src/components/SameBcHierarchyTable/SameBcHierarchyTable.tsx
- src/components/widgets/PickListPopup/PickListPopup.tsx
- src/interfaces/widget.ts
fix/issue-51 Convert type of hierarchy List cell with drilldown meta: text -> field
> Convert type of hierarchy List cell with drilldown meta: text -> field (#51)

- src/components/widgets/PickListPopup/PickListPopup.tsx
Disable pagination for PickListPopup with FullHierarchy
> Disable pagination for PickListPopup with FullHierarchy

- src/actions/actions.ts
- src/epics/view.ts
See https://github.com/tesler-platform/tesler-ui/issues/53
And another solution for a related issue (https://github.com/tesler-platform/tesler-ui/issues/35)
> fix/issue-53 Sending request to rowMeta when ForceActive field change

- src/components/HierarchyTable/HierarchyTable.less
- src/components/HierarchyTable/HierarchyTable.tsx
- src/components/ui/Pagination/Pagination.tsx
> Fix layout for hierarchy tables and disable pagination if not required

- src/components/Field/Field.tsx
- src/middlewares/requiredFieldsMiddleware.ts
> Fix wrong behavior of number fields

- src/actions/actions.ts
- src/epics/data.ts
- src/epics/screen.ts
> Fix required field check crash on autosave caused by drilldown.

- src/middlewares/autosaveMiddleware.ts
> Fix wrong autosave widget name source.

- src/components/HierarchyTable/HierarchyTable.less
- src/components/HierarchyTable/HierarchyTable.tsx
> Fix treeData tables style

- src/interfaces/navigation.ts
UI support of https://github.com/tesler-platform/tesler/issues/18
> Expanded navigation interfaces

- src/components/HierarchyTable/HierarchyTable.tsx
> Don't display expanded treeData records without data

- webpack.config.js
Adding to the config Translating ES2015 modules from npm to support IE11
> webpack.config marked lib transpile (#88)

- src/components/ColumnTitle/ColumnFilter.tsx
- src/components/widgets/PickListPopup/PickListPopup.tsx
> Fix fields filtering

- src/components/index.ts
- src/components/ui/Multivalue/MultivalueList.tsx
> Export the TemplatedTitle component and change the fieldTitle type in MultivalueList

- src/actions/actions.ts
- src/components/widgets/FormWidget/FormWidget.tsx
- src/epics/data.ts
- src/epics/view.ts
- src/reducers/view.ts
> Fix forceActive and fields validation

- src/actions/actions.ts
- src/assets/i18n/en.json
- src/assets/i18n/ru.json
- src/components/ColumnTitle/ColumnFilter.tsx
- src/components/widgets/TableWidget/TableWidget.tsx
- src/epics/router.ts
- src/reducers/screen.ts
- src/utils/filters.ts
> Support for drilldowns with sorting, reset all filters at once

- src/epics/view.ts
> Return sending to backend unfilled required fields (null) on forceActive change

- src/interfaces/widget.ts
rename parameter for documentation
> rename parameter for documentation

- src/epics/data.ts
> Fix app crash on autosave

- src/components/Field/Field.tsx
- src/components/HierarchyTable/HierarchyTable.tsx
- src/components/index.ts
> Pass hierarchy depth level to custom fields (#135)

- src/assets/i18n/en.json
- src/assets/i18n/ru.json
- src/components/ColumnTitle/ColumnFilter.tsx
- src/components/widgets/TableWidget/TableWidget.less
- src/components/widgets/TableWidget/TableWidget.tsx
- src/interfaces/bc.ts
- src/interfaces/filters.ts
> Support for predefined filters

- src/actions/actions.ts
- src/middlewares/__tests__/__mocks__/store.json
- src/middlewares/__tests__/__mocks__/store1.json
- src/middlewares/__tests__/autosaveMiddleware.test.ts
- src/middlewares/autosaveMiddleware.ts
> sendOperation action added to needSaveAction list (#144)

- src/interfaces/widget.ts
- Extended WidgetOptions Interface by tableActions option
- Added ITableActions interface which describes tableActions position relatively table for the time being
> Preliminary work for `EditableTable` widget (#152):

- src/components/ColumnTitle/ColumnFilter.tsx
- src/components/FileUpload/FileUpload.tsx
- src/components/ui/Pagination/Pagination.tsx
- src/components/ui/PickInput/PickInput.tsx
> temporary fix for react invariant #300 and #310 errors crashing the application due to react-i18next usage (#167)

- src/epics/data.ts
- src/epics/view.ts
> Missing `popup` existence check in ajax reposnse catch-handler causing application crash (#180)

- src/components/widgets/AssocListPopup/AssocTable.tsx
> `<AssocTable />` should have a functional `selectAll` checkbox (#193)

- CHANGELOG.md
- package.json
- src/components/Multivalue/MultivalueField.tsx
MultivalueField loses BC while screen changing (#197)
> Version update 1.11.1

- src/components/Field/Field.tsx
- src/components/ui/TextArea/TextArea.tsx
- src/interfaces/rowMeta.ts
> Fields processing improvements

- src/components/ui/CheckboxPicker/CheckboxPicker.tsx
- src/components/ui/Dictionary/Dictionary.tsx
- src/components/ui/HistoryField/HistoryField.tsx
- src/components/ui/Link/Link.tsx
- src/components/ui/MultiField/MultiField.tsx
- src/components/ui/Multivalue/MultivalueHover.tsx
- src/components/ui/Multivalue/MultivalueList.tsx
- src/components/ui/Multivalue/MultivalueTag.tsx
- src/components/ui/NumberInput/NumberInput.tsx
- src/components/ui/Pagination/Pagination.tsx
- src/components/ui/PickInput/PickInput.tsx
- src/components/ui/Popup/Popup.tsx
- src/components/ui/RadioButton/RadioButton.tsx
- src/components/ui/ReadOnlyField/ReadOnlyField.tsx
- src/components/ui/Select/Select.tsx
> Exported ownProps interfaces of all src/components/ui components (#219)

- src/assets/i18n/en.json
- src/assets/i18n/ru.json
- src/components/InlinePickList/InlinePickList.tsx
- src/components/Multivalue/MultivalueField.tsx
- src/components/PickListField/PickListField.tsx
- src/components/ui/Dictionary/Dictionary.tsx
- src/components/ui/Multivalue/MultivalueTag.less
- src/components/ui/Multivalue/MultivalueTag.tsx
- src/components/ui/NumberInput/NumberInput.tsx
- src/components/ui/PickInput/PickInput.tsx
> Support for the 'placeholder' property in the all tesler's field types

- src/components/FullHierarchyTable/FullHierarchyTable.test.tsx
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/components/widgets/FormWidget/FormWidget.test.tsx
- src/components/widgets/FormWidget/FormWidget.tsx
- src/components/widgets/PickListPopup/PickListPopup.test.tsx
- src/components/widgets/PickListPopup/PickListPopup.tsx
- src/components/widgets/TableWidget/TableWidget.test.tsx
- src/components/widgets/TableWidget/TableWidget.tsx
- src/interfaces/widget.ts
added checks of 'hidden: true' to FullHierarchyTable, FormWidget, PickListPopup and TableWidget widgets (#230)
> added hidden to WidgetFieldBase

- src/components/FullHierarchyTable/FullHierarchyTable.test.tsx
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/components/widgets/FormWidget/FormWidget.test.tsx
- src/components/widgets/FormWidget/FormWidget.tsx
- src/components/widgets/PickListPopup/PickListPopup.test.tsx
- src/components/widgets/PickListPopup/PickListPopup.tsx
- src/components/widgets/TableWidget/TableWidget.test.tsx
- src/components/widgets/TableWidget/TableWidget.tsx
- src/interfaces/widget.ts
Also added checks of 'hidden: true' to FullHierarchyTable, FormWidget, PickListPopup and TableWidget widgets (#230)
> Added property 'hidden' to WidgetFieldBase interface

- src/components/widgets/TableWidget/TableWidget.less
- src/components/widgets/TableWidget/TableWidget.tsx
See #234 
The optional  `showDots` property is added in the TableWidget component. When it's true - the table will show the 3 points (record's menu) on all records at once.
> Add the ability to customize display dots-menu on the records

- src/epics/view.ts
- src/interfaces/data.ts
- src/interfaces/operation.ts
> Key 'postInvokeConfirm' excluded from customActions API (#237)

- src/epics/view.ts
> fixed error if sendOperation payload doesn't contains postActions (#243)

- src/index.ts
> Exported  ActionPayloadTypes, AnyAction and utilities from actions-utils

- src/epics/data.ts
> Data fetch should be initiated after successful save operation (#247)

- src/components/widgets/TableWidget/TableWidget.tsx
See #234
The optional `disableDots` property is added in the TableWidget component. When it's true - the table will not show the 3 points (record's menu) on hover.
The optional `controlColumns` property is an array of custom columns and their location.
> Add the ability to add customized columns in the table

- src/epics/data.ts
> fixed error computing `limit` (#264)

- src/epics/data.ts
saveAssociations action bcName to API Query Parameters request.
> bcName to API Query Parameters request (#213)

- package.json
saveAssociations action bcName to API Query Parameters request. Alpha version ^
> Alpha version ^

- src/components/widgets/TableWidget/TableWidget.tsx
> Table filtration and sorting not working due to missing prop dependency in columns hook (#270)

- package.json
- src/components/widgets/TableWidget/TableWidget.tsx
- src/epics/view.ts
1.14.4-alpha.0
- TableWidget (...) simple preInvoke
- Tag assocValueKey fix
> 1.14.4-alpha.0

- package.json
- src/Provider.tsx
- src/middlewares/preInvokeMiddleware.tsx
1.14.5-alpha.0
preInvoke Middleware
> 1.14.5-alpha.0

- package.json
- src/middlewares/preInvokeMiddleware.tsx
Alpha 1.14.6 alpha.0
preInvoke middleware
> alpha version ^1.14.6-alpha.0

- package.json
- src/actions/actions.ts
- src/components/FullHierarchyTable/FullHierarchyTable.test.tsx
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/index.ts
- src/interfaces/view.ts
- src/reducers/view.ts
alpha version ^1.15.1-alpha.0
Basis for the save number of Tablewidget records
Select all checkbox in FullHierarchyTable
> alpha version ^1.15.1-alpha.0

- package.json
- src/components/Field/Field.tsx
- src/components/FullHierarchyTable/FullHierarchyTable.less
- src/components/FullHierarchyTable/FullHierarchyTable.test.tsx
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/components/ui/SearchHightlight/SearchHightlight.tsx
- src/components/widgets/AssocListPopup/AssocListPopup.tsx
- src/components/widgets/PickListPopup/PickListPopup.tsx
- src/utils/strings.ts
PreInvokeMiddleware
Select all checkbox in FullHierarchyTable
Basis for the save number of Tablewidget records
FullHierarcy search support
> alpha version ^1.15.3-alpha.0

- package.json
- src/components/ui/Popup/Popup.tsx
- src/components/widgets/PickListPopup/PickListPopup.less
- src/components/widgets/PickListPopup/PickListPopup.tsx
- src/interfaces/view.ts
alpha version ^1.15.4-alpha.0
Fixes:
- PreInvokeMiddleware
- Select all checkbox in FullHierarchyTable
- Basis for the save number of Tablewidget records
- FullHierarcy search support
- PickListPopup remove footer buttons and fix title
> alpha version ^1.15.4-alpha.0

- package.json
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
Alpha version ^1.15.7-alpha.0
Fix crash FullHierarcy
> Alpha version ^1.15.7-alpha.0

- package.json
- src/components/FullHierarchyTable/FullHierarchyTable.less
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
alpha version ^1.15.9-alpha.0
Fixes:
- Alignment of columns in the FullHierarchyTable, due to setting the width
> Alpha version ^1.15.9-alpha.0

- package.json
- src/actions/actions.ts
- src/components/FullHierarchyTable/FullHierarchyTable.test.tsx
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/components/ui/Popup/Popup.tsx
- src/components/widgets/PickListPopup/PickListPopup.less
- src/components/widgets/PickListPopup/PickListPopup.tsx
- src/index.ts
- src/interfaces/view.ts
- src/reducers/view.ts
alpha version ^1.15.11-alpha.0
Fixes:
Alignment of columns in the FullHierarchyTable, due to setting the width
Select all checkbox in FullHierarchyTable
Basis for the save number of Tablewidget records
PickListPopup remove footer buttons and fix title
> Alpha version ^1.15.11-alpha.0

- package.json
- src/components/widgets/PickListPopup/PickListPopup.tsx
- src/components/widgets/TableWidget/TableWidget.tsx
Alpha version ^1.15.13-alpha.0
* Fixed bug when preInvoke doesn`t work if you use operation in dots menu
> Alpha version ^1.15.13-alpha.0

- src/components/ui/Popup/Popup.tsx
- src/components/widgets/PickListPopup/PickListPopup.less
- src/components/widgets/PickListPopup/PickListPopup.tsx
Removed buttons from footer in PickListPopup.
Fixed title in PickListPopup.
> PickListPopup remove footer buttons and fix title

- src/components/Multivalue/MultivalueField.test.tsx
- src/components/Multivalue/MultivalueField.tsx
- src/components/PickListField/PickListField.tsx
- src/components/ui/Multivalue/MultivalueTag.tsx
- src/components/ui/PickInput/PickInput.tsx
- src/epics/view.ts
MVG field open icon inactive without popup widget rowMeta (#299)
Checking popup widget rowMeta from mvg field. While rowMeta dont receive the icon open popup changed to spiner.
> MVG popup icon spiner

- package.json
- tsconfig.json
- webpack.config.js
- yarn.lock
Reverts tesler-platform/tesler-ui#281
description WIP
> Revert "rebuild speedup"

- src/components/View/View.tsx
> Layout fix to let customLayout be set

- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/pull-request.yml
See https://github.community/t/github-sha-not-always-correct/117863
> Update `actions/checkout` action to fix broken pipelines with commit hash mismatch

- src/components/ColumnTitle/ColumnFilter.tsx
- src/components/ColumnTitle/ColumnTitle.tsx
- src/components/Field/Field.tsx
- src/components/FullHierarchyTable/FullHierarchyFilter.tsx
- src/components/FullHierarchyTable/FullHierarchyTable.less
- src/components/FullHierarchyTable/FullHierarchyTable.test.tsx
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/components/FullHierarchyTable/hierarchySearchCache.test.ts
- src/components/FullHierarchyTable/hierarchySearchCache.ts
- src/components/ui/SearchHightlight/SearchHightlight.tsx
- src/components/widgets/AssocListPopup/AssocListPopup.tsx
- src/components/widgets/PickListPopup/PickListPopup.tsx
- src/interfaces/widget.ts
- src/utils/strings.ts
New FullHierarchy feature. Search and filter data values ​​by user row. Based on **tesler-ui** `FullHierarchyTable` component (#241). Filter operation performs transformation data tree according rules:
- based on the search string, the hierarchy tree should contain only branches which values ​​from the search are present.
- founded values have a different font.
- new tree ​​should be opened to the deepest founded value.
- apply filters on different columns at the same time.
- reset filters when popup closed (AssocListPopup, PickListPipup).
Filter column operation ebabled when field row-meta has key `filterable: true`.
New custom DropDown filter form. 
Changes in the transfer of data to a deeper level. The selection of elements at each level has been replaced by a single selection at the …
> FullHierarchy table column search

- src/components/ColumnTitle/ColumnFilter.tsx
- src/components/ui/DatePickerField/DatePickerField.tsx
> Filter by date does not keep its state and erroneously shows time (#354)

- src/epics/data.ts
- src/epics/view.ts
- src/interfaces/operation.ts
- src/middlewares/preInvokeMiddleware.tsx
- src/middlewares/requiredFieldsMiddleware.ts
- src/utils/__tests__/operations.test.tsx
- src/utils/operations.ts
> new `actionRole` property allowing custom operations to be be processed as a standard operation (#356)

- src/components/Field/Field.tsx
- src/epics/data.ts
- src/middlewares/autosaveMiddleware.ts
Added prop `tooltipPlacement` to `Field` component
> Refactored AutoSaveMiddleware (#376)

- package.json
- src/components/Field/Field.tsx
- src/components/ui/TextArea/TextArea.tsx
- src/interfaces/widget.ts
- yarn.lock
Upgraded antd to 3.26.18 in aims of fixing https://github.com/ant-design/ant-design/issues/21697
> Draft: Added 'maxInput' param to WidgetFieldBase

- src/components/Field/Field.tsx
- src/components/ui/Dictionary/Dictionary.test.tsx
- src/components/ui/Dictionary/Dictionary.tsx
- src/interfaces/data.ts
- src/interfaces/widget.ts
> <Dictionary/>: added `multiple` mode for several items selecting

- src/components/Field/Field.tsx
- src/components/ui/ReadOnlyField/ReadOnlyField.less
see (https://github.com/tesler-platform/tesler-ui/issues/389)
> ReadOnly field show error on TableWidget

- package.json
- src/components/Field/Field.test.tsx
- src/components/Field/Field.tsx
- src/components/ui/TextArea/TextArea.test.tsx
- src/components/ui/TextArea/TextArea.tsx
- src/interfaces/widget.ts
- yarn.lock
see #363 
Added availability to set maximum number of characters to fields of type `input` and `text`.
Upgraded antd to 3.26.18 in aims of fixing https://github.com/ant-design/ant-design/issues/21697
> Added 'maxInput' param to WidgetFieldBase (#363)

- src/components/View/View.tsx
- src/components/Widget/Widget.test.tsx
- src/components/Widget/Widget.tsx
- src/components/ui/DashboardLayout/DashboardLayout.tsx
- src/interfaces/widget.ts
Adds ability to exclude custom widgets from being wrapped in <Card /> component
> Add ability to exclude widget from being wrapped in <Card />

- src/components/widgets/AssocListPopup/AssocListPopup.tsx
- src/hooks/useAssocRecords.ts
See (#415)
`selectedRecords` function returns pending data item and data items with _associate=true
> AssocListPopup Tag fix

- src/components/widgets/TableWidget/TableWidget.tsx
See #408 
Added extention of header to TableWidget.
> Customization of Table widget's header

- src/components/widgets/AssocListPopup/AssocListPopup.test.tsx
- src/components/widgets/AssocListPopup/AssocListPopup.tsx
see https://github.com/tesler-platform/tesler-ui/issues/410
> deleting a tag deletes all child associations in AssocListPopup

- src/components/Field/Field.tsx
- src/components/TemplatedTitle/TemplatedTitle.tsx
- src/components/Widget/Widget.test.tsx
- src/components/Widget/Widget.tsx
- src/components/widgets/InfoWidget/InfoWidget.tsx
- src/components/widgets/InfoWidget/__test__/InfoWidget.test.tsx
- src/components/widgets/InfoWidget/components/InfoCell.less
- src/components/widgets/InfoWidget/components/InfoCell.tsx
- src/components/widgets/InfoWidget/components/InfoRow.less
- src/components/widgets/InfoWidget/components/InfoRow.tsx
- src/components/widgets/InfoWidget/components/InfoValueWrapper.less
- src/components/widgets/InfoWidget/components/InfoValueWrapper.tsx
- src/components/widgets/InfoWidget/components/__tests__/InfoCell.test.tsx
- src/components/widgets/InfoWidget/components/__tests__/InfoRow.test.tsx
- src/components/widgets/InfoWidget/components/__tests__/InfoValueWrapper.test.tsx
- src/interfaces/widget.ts
> Added `<InfoWidget/>` component

- src/Provider.tsx
> Bug of combination core and custom initial states is fixed (#445)

- src/components/ModalInvoke/ModalInvoke.tsx
> Ability to pass className to ModalInvoke component

- src/interfaces/data.ts
- src/interfaces/view.ts
> Field `template` is added to `ViewMetaResponse` interface (#431)

- src/components/Field/Field.tsx
- src/components/widgets/FormWidget/FormWidget.tsx
- src/epics/data.ts
- src/interfaces/widget.ts
see https://github.com/tesler-platform/tesler-ui/issues/420
> Disable error tooltip

- src/components/Widget/Widget.tsx
- src/components/widgets/AssocListPopup/AssocListPopup.tsx
- src/components/widgets/PickListPopup/PickListPopup.tsx
> Unify PickListPopup and AssocListPopup showed prop

- src/components/ui/Dictionary/Dictionary.test.tsx
- src/components/ui/Dictionary/Dictionary.tsx
> Dictionary: Displaying of a placeholder is fixed (#462)

- src/epics/data.ts
> Cancel proccessing 'fetchBcData' request after logout

- src/components/Widget/Widget.test.tsx
- src/components/Widget/Widget.tsx
- src/interfaces/widget.ts
> popup widgets are shown even when not invoked (#459)

- src/components/ui/Popup/PopupFooter.less
- src/components/ui/Popup/PopupFooter.tsx
- src/components/ui/TreeVirtualized/TreeVirtualized.tsx
- src/components/ui/TreeVirtualized/TreeVirtualizedNode.less
- src/components/ui/TreeVirtualized/TreeVirtualizedNode.tsx
- src/components/ui/TreeVirtualized/__tests__/TreeVirtualized.test.tsx
- src/components/ui/TreeVirtualized/__tests__/TreeVirtualizedNode.test.tsx
- src/components/widgets/FlatTree/FlatTree.less
- src/components/widgets/FlatTree/FlatTree.tsx
- src/components/widgets/FlatTree/FlatTreePopup.tsx
- src/components/widgets/FlatTree/__tests__/FlatTreePopup.test.tsx
- src/components/widgets/FlatTree/useMultipleSelect.ts
- src/components/widgets/FlatTree/useSingleSelect.ts
- src/interfaces/tree.ts
- src/interfaces/widget.ts
draft for `FlatTreePopup` behaving like `AssocListPopup`
> widget option `multiple` to allow selecting multiple records on `<FlatTreePopup />` widgets

- src/assets/i18n/en.json
- src/assets/i18n/ru.json
- src/components/ui/ErrorPopup/ErrorPopup.less
- src/components/ui/ErrorPopup/ErrorPopup.test.tsx
- src/components/ui/ErrorPopup/ErrorPopup.tsx
- src/interfaces/view.ts
- src/utils/api.ts
> ErrorPopup: an availability to copy details of error is added (#490)

- src/components/ui/TreeVirtualized/TreeVirtualized.tsx
- src/components/ui/TreeVirtualized/__tests__/TreeVirtualized.test.tsx
- src/components/ui/TreeVirtualized/__tests__/TreeVirtualizedNode.test.tsx
- src/utils/__tests__/tree.test.ts
- src/utils/tree.ts
> `<TreeVirtualized />` should not rely on input data being presorted: they might be not, which leads to children nodes expanding wrong direction

- src/actions/actions.ts
- src/interfaces/operation.ts
- src/interfaces/view.ts
- src/reducers/view.ts
see #507
`calleeWidgetName` is added to interface PopupData
> `icon` and `showOnlyIcon` are added to interface OperationGroup (#507)

- src/components/widgets/TableWidget/TableWidget.tsx
TableWidget.tsx force floating menu top position recalculation when table data have one row
> fix: floating menu with single row

- CHANGELOG.md
- package.json
- src/utils/__tests__/tree.test.ts
- src/utils/tree.ts
> Application crash in `assignTreeLinks` on orphaned records (#524)

- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/utils/hierarchy.ts
Added ability to set width of last column, fixed -Infinitypx value of maxDepth
> Full hierarchy list layout fixes

- src/components/FullHierarchyTable/FullHierarchyTable.less
- src/components/HierarchyTable/HierarchyTable.less
- src/components/HierarchyTable/HierarchyTable.tsx
Fixed Hierarchy and FullHierarchy rows vertical align which should be **top** as on Table widget.
> fix Hierarchy and FullHierarchy vertical align

- src/components/View/View.tsx
- src/components/View/__tests__/View.test.tsx
- src/components/Widget/Widget.test.tsx
- src/components/Widget/Widget.tsx
- src/components/ui/DashboardLayout/DashboardLayout.tsx
- src/components/ui/DashboardLayout/__tests__/DashboardLayout.test.tsx
see #570 
New prop `customSpinner` is added to `View` component which is passed to `Widget` component
> New prop `customSpinner` is added (#570)

- src/reducers/screen.ts
Value in filter is compared with itself.
> Error in remove filter action.

- src/components/ui/ReadOnlyField/ReadOnlyField.less
Text doesn't wrap correctly in IE11.
> Fix IE11 text wrap problem

- src/components/ui/Multivalue/MultivalueTag.tsx
Assoc load two times from server when user click on icon.
> fix: assoc load two times

- src/components/Field/Field.test.tsx
- src/hooks/useDrillDownUrl.ts
DrillDown doesn't respect field meta 'drillDown' flag and takes in account only row-meta.
> fix DrillDown doesn't respect field meta

- package.json
- src/actions/actions.ts
- src/assets/i18n/en.json
- src/assets/i18n/ru.json
- src/components/ui/ErrorPopup/ErrorPopup.test.tsx
- src/components/ui/ErrorPopup/ErrorPopup.tsx
- src/epics/index.ts
- src/epics/utils.ts
- src/interfaces/session.ts
- src/middlewares/actionsHistoryMiddleware.ts
- src/middlewares/index.ts
- src/reducers/session.ts
- src/utils/actionsHistory.ts
- src/utils/configureStore.ts
- src/utils/exportState.ts
- yarn.lock
see #532
If `Save Info For Developers` button is pressed, then these files downloads to user device:
* A screenshot with error
* Redux store as JSON file
> An availability to export info for developers is added (#532)

- src/epics/view/__tests__/sendOperation.test.ts
- src/epics/view/sendOperation.ts
> Filters and sorters are added to `custom-action` request params (#616)

- .github/workflows/documentation-tests.yml
In case you have a branch with your cool feature and you'd like to check out if your feature doesn't breaks clients project.
Here is the workflow that triggers autotests of tesler-doc.
Leave a comment with text `/testDoc` on your PR
Leave a comment with text `/withBackTestDoc <backend-repo> <backend-ref>`, where
`<backend-repo>` – name of backend repository (commonly tesler-platform/tesler),
`<backend-ref>` – the branch, tag or SHA to checkout.
For example: `/withBackTestDoc tesler-platform/tesler master`
> Run tesler-doc autotests

- src/epics/router/__tests__/drilldown.test.ts
- src/epics/router/drilldown.ts
> clear filters by drilldown operation (#627)

- src/components/ModalInvoke/ModalInvoke.test.tsx
- src/components/ModalInvoke/ModalInvoke.tsx
- src/interfaces/operation.ts
> ModalInvoke: Customization of button labels is added (#633)

- src/components/Field/Field.test.tsx
- src/components/FullHierarchyTable/FullHierarchyTable.tsx
- src/components/HierarchyTable/HierarchyTable.tsx
- src/components/SameBcHierarchyTable/SameBcHierarchyTable.tsx
- src/components/ui/Multivalue/MultivalueHover.less
- src/components/ui/Multivalue/MultivalueHover.tsx
- src/components/widgets/TableWidget/TableWidget.tsx
> Need to add the ability to set background color for multivalueHover field type (#635)

- src/components/RowOperations/RowOperationsButton.less
- src/components/RowOperations/RowOperationsButton.tsx
- src/components/RowOperations/__tests__/RowOperationsButton.test.tsx
> `<RowOperationsButton />` should open menu in IE (#646)

- package.json
- src/components/ColumnTitle/ColumnTitle.tsx
- src/components/Field/Field.tsx
- src/components/Multivalue/MultiValueListRecord.tsx
- src/components/SameBcHierarchyTable/SameBcHierarchyTable.tsx
- src/index.ts
- src/interfaces/enums/filters.ts
- src/interfaces/enums/objectMap.ts
- src/interfaces/enums/operation.ts
- src/interfaces/enums/router.ts
- src/interfaces/enums/view.ts
- src/interfaces/enums/widget.ts
- src/utils/filters.ts
- yarn.lock
- Using of duplications of tesler-schema's const enums is added; 
- Duplications of tesler's const enums are added
> Const enums duplications

- src/actions/actions.ts
- src/components/ColumnTitle/ColumnFilter.tsx
- src/components/ColumnTitle/ColumnTitle.tsx
- src/components/ColumnTitle/__tests__/ColumnTitle.test.tsx
- src/components/Field/Field.test.tsx
- src/components/Multivalue/MultivalueField.test.tsx
- src/components/Multivalue/MultivalueField.tsx
- src/components/PickListField/PickListField.tsx
- src/components/Widget/Widget.tsx
- src/epics/view/sendOperationAssociate.ts
- src/interfaces/view.ts
- src/reducers/view.ts
See #619
Additional: now condition of showing widget depends on `name` not `bcName`.
> In case field type is pickList then ColumnFilter shows AssocListPopup for filtering

- src/interfaces/widget.ts
> `null` is added as possible value of  `CustomWidgetConfiguration.card`

- src/components/ui/NumberInput/NumberInput.test.tsx
- src/components/ui/NumberInput/NumberInput.tsx
> NumberInput is reanimated after been broken by #641 

- src/components/Widget/Widget.test.tsx
- src/components/Widget/Widget.tsx
- src/components/widgets/ViewNavigationWidget/ViewNavigationWidget.test.tsx
- src/components/widgets/ViewNavigationWidget/ViewNavigationWidget.tsx
- src/interfaces/widget.ts
See #702
- `ViewNavigationWidget` should accept various values of `navigationLevel`
- `NavigationTabsWidget` should be included to widgets common stream
> ViewNavigationWidget fix (#702)

- src/epics/data.ts
- src/epics/data/__tests__/saveAssociationsActive.test.ts
- src/epics/data/saveAssociationsActive.ts
> `saveAssociationsActive` sends request with truly associated items only

- CHANGELOG.md
- package.json
- src/components/ModalInvoke/ModalInvoke.tsx
- src/epics/data.ts
- src/epics/data/__tests__/saveAssociationsActive.test.ts
- src/epics/data/saveAssociationsActive.ts
- yarn.lock
* devDependency axios does not match with declared peer dependency ([#722](https://github.com/tesler-platform/tesler-ui/pull/722))
* `saveAssociationsActive` sends request with truly associated items only ([#728](https://github.com/tesler-platform/tesler-ui/pull/728))
* null check is added to `ModalInvoke`'s `mapStateToProps` ([731](https://github.com/tesler-platform/tesler-ui/pull/731))
> Release 1.33.2

- src/components/ColumnTitle/ColumnFilter.tsx
- src/components/ColumnTitle/__tests__/ColumnFilter.test.tsx
issues [70](https://github.com/tesler-platform/tesler-demo/issues/70)
> Filter values are not removed after pushing a "Clear" button

- src/components/Widget/Widget.test.tsx
- src/components/Widget/Widget.tsx
> Displaying a debug panel for custom widgets (#740)

- package.json
- src/assets/i18n/en.json
- src/assets/i18n/ru.json
- src/components/ColumnTitle/ColumnFilter.tsx
- src/components/FilterPopup/FilterPopup.tsx
- src/components/ui/FilterField/FilterField.test.tsx
- src/components/ui/FilterField/FilterField.tsx
- src/components/ui/FilterField/components/RangePicker.less
- src/components/ui/FilterField/components/RangePicker.test.tsx
- src/components/ui/FilterField/components/RangePicker.tsx
- src/interfaces/filters.ts
- src/reducers/screen.ts
- src/utils/__tests__/filters.test.ts
- src/utils/filters.ts
- yarn.lock
see #710 
It is the replacement of #733
> Added ability to filter date fields by range (#710)

- CHANGELOG.md
- package.json
- src/assets/i18n/en.json
- src/assets/i18n/ru.json
- src/components/ColumnTitle/ColumnFilter.tsx
- src/components/ColumnTitle/__tests__/ColumnFilter.test.tsx
- src/components/FilterPopup/FilterPopup.tsx
- src/components/Widget/Widget.test.tsx
- src/components/Widget/Widget.tsx
- src/components/ui/FilterField/FilterField.test.tsx
- src/components/ui/FilterField/FilterField.tsx
- src/components/ui/FilterField/components/RangePicker.less
- src/components/ui/FilterField/components/RangePicker.test.tsx
- src/components/ui/FilterField/components/RangePicker.tsx
- src/interfaces/filters.ts
- src/reducers/screen.ts
- src/utils/__tests__/filters.test.ts
- src/utils/filters.ts
- yarn.lock
* The ability to filter dates fields by range ([#710](https://github.com/tesler-platform/tesler-ui/issues/710))
* Displaying a debug panel for custom widgets ([#740](https://github.com/tesler-platform/tesler-ui/issues/740))
* Removing filters after click on "clear" button ([tesler-demo_#70](https://github.com/tesler-platform/tesler-demo/issues/70))
> Release 1.34.0
